### PR TITLE
Auto-generate All Actions From The API

### PR DESCRIPTION
**Pull request by nmaludy**
**Note: This is a breaking change**

Previously this pack only implemented a few actions from the API and they were coded up manually using `requests`. I wanted to improve this by auto-generating the actions and also implementing the complete API.

Both goals are accomplished with this PR, the only real debate i had was whether or not to name actions like:

`foreman.hosts.index` or `foreman.hosts_index`

I chose the latter because that's consistent with what other packs do. Basically the first word in every action (before the first _) is the "collection" that API call is for.

Comments are much appreciated!

### CODE REVIEW

**Comment by nmaludy** [comment]
I've separated out all of the auto-generated actions into a new PR #4 so that this PR is easier to review.

**Comment by nullkarma** [comment]
@nmaludy thanks for implementing the whole foreman api. I really appreciate that. I'll have a look into it

**Review by nullkarma — COMMENTED** [review]
What is your opinion on naming the action like `parameters::operation`, so it's "grouped" by api endpoint? Take `activation_keys.available_host_collections` as an example. It might be easier to read, imho. Especially the really long action names.

**Comment by nmaludy** [comment]
@nullkarma yeah i had gone back-forth on that... the reason i landing on doing `endpoint_function_name_xxx` was because that's consistent with other packs.

In this case the number of actions is fairly large and i agree it would make sense to have a different separator for the endpoint.

Luckily, since they are all auto-generated it takes literally 2 seconds to change this. Look for a push here in a few.

**Comment by nullkarma** [comment]
@nmaludy Thanks for your commitment. I am curious to know where'd you get the complete api definition from? Really like your work.

@LindsayHill ready to be merged.

**Comment by nmaludy** [comment]
@nullkarma Updated this branch as well with the generator updates for `endpoint.operation` format.

**Pull request merged**
