### PR TITLE
Update API to Foreman version 1.15

### PR DESCRIPTION
**Pull request by nmaludy**
This updates the actions to be compatible with the Foreman API version `1.15`

### CODE REVIEW

**Comment by nmaludy** [comment]
@nullkarma could you check this out when you get a chance?

**Comment by nullkarma** [comment]
@nmaludy will do till the end of this week. Thanks for the update.

**Comment by LindsayHill** [comment]
@nullkarma you get a chance to take a look at this one?

**Comment by nullkarma** [comment]
sorry. took a while. looks good to me. thanks for the update

**Pull request merged**
